### ISSUE TITLE
Can't compile with ghc-9.2.1-alpha2

### ISSUE THREAD

**Issue by l29ah** [ndmitchell/record-dot-preprocessor#42]
```
[1 of 2] Compiling Compat           ( plugin/Compat.hs, dist/build/Compat.o, dist/build/Compat.dyn_o )

plugin/Compat.hs:46:24: error:
    • Couldn't match type ‘SrcSpan’
                     with ‘SrcSpanAnn' (EpAnn AnnListItem)’
      Expected: LHsType (GhcPass p)
        Actual: GenLocated SrcSpan (HsType (GhcPass p))
    • In the expression:
        noL $ HsTyVar noE NotPromoted $ noL $ hsLTyVarName x
      In an equation for ‘hsLTyVarBndrToType’:
          hsLTyVarBndrToType x
            = noL $ HsTyVar noE NotPromoted $ noL $ hsLTyVarName x
   |
46 | hsLTyVarBndrToType x = noL $ HsTyVar noE NotPromoted $ noL $ hsLTyVarName x
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

plugin/Compat.hs:46:38: error:
    • Couldn't match type ‘NoExtField’ with ‘EpAnn [AddEpAnn]’
      Expected: XTyVar (GhcPass p)
        Actual: NoExtField
    • In the first argument of ‘HsTyVar’, namely ‘noE’
      In the first argument of ‘($)’, namely ‘HsTyVar noE NotPromoted’
      In the second argument of ‘($)’, namely
        ‘HsTyVar noE NotPromoted $ noL $ hsLTyVarName x’
   |
46 | hsLTyVarBndrToType x = noL $ HsTyVar noE NotPromoted $ noL $ hsLTyVarName x
   |                                      ^^^

plugin/Compat.hs:73:62: error:
    • Data constructor not in scope:
        HsIB
          :: NoExtField
             -> GenLocated SrcSpanAnnA (HsType GhcPs)
             -> GenLocated SrcSpanAnnA (HsSigType (GhcPass 'Parsed))
    • Perhaps you meant ‘HsIf’ (imported from GHC.Hs)
   |
73 | mkTypeAnn expr typ = noL $ ExprWithTySig noE expr (HsWC noE (HsIB noE typ))
   |                                                              ^^^^

plugin/Compat.hs:130:50: error:
    Data constructor not in scope:
      NoSourceText :: GHC.Types.SourceText.SourceText
    |
130 | qualifiedImplicitImport x = noL $ ImportDecl noE NoSourceText (noL x) Nothing NotBoot False
    |                                                  ^^^^^^^^^^^^
```

**Comment by ndmitchell** [comment]
Because of the significant changes between each GHC version, the code inevitably requires adjustment. My inclination is to wait for RC1 to do those, because it's very sensitive to all the little changes, and I don't want to repeat the work. But I'd happily accept a diff before then.

**Comment by ndmitchell** [comment]
See #43 for some start to this change, which is probably worth building off.

**Comment by phadej** [comment]
`record-dot-preprocessor` should have bounds (atleast on) `ghc` dependency. It's 99% sure it won't just work with next major `ghc` version.

For now I made revisions for all `-0.2.*` versions, e.g. https://hackage.haskell.org/package/record-dot-preprocessor-0.2.14/revisions/

**Comment by ndmitchell** [comment]
Thanks for the revisions. Agreed bounds are useful - those are added in #50 so will wait for that to land.

**Comment by ndmitchell** [comment]
Released as 0.2.15
